### ISSUE TITLE
Previous disconnect still processing

### ISSUE THREAD

**Issue by dbashyal** [magento/meta-for-magento2#54]
Dear Support,

I recently disconnected my Magento account from Facebook and am now interested in re-establishing the connection. However, I’ve noticed that the status has been displaying “Previous disconnect still processing” for a few hours now. 

![facebook-magento-re-connection-error](https://github.com/magento/meta-for-magento2/assets/833986/46278264-0ef2-4223-8f66-c8fff0c968dc)

I understand that these processes can take some time, but I was wondering if you could provide any insight into the typical duration for this process. This would greatly assist me in planning when to attempt the reconnection.

Thank you in advance for your assistance and I look forward to your response.

Best regards.
Damu

**Comment by ponaravind-outdoorgoats** [comment]
Did You found any solution? Im facing this same issue in magento 2.4.6-p2. I tried reinstalling the module and [](https://www.facebook.com/settings?tab=business_tools&section=active) I removed my magento here. Nothing works so far.

**Comment by zlik** [comment]
@jczhuoMeta in case it's a known issue

**Comment by jczhuoMeta** [comment]
Hello, this is by design to ensure all the underlying data has been completely removed for compliance reason.

If this happens again, here're the possible resolutions:
1. Usually it will resolve itself in hours
2. If it still not working, try go to config:
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/52e762ec-2155-40c5-8f7e-6b61ddb55325">
This will assign a new ID and should allow you to restart config immediately.
3. If above options not working, please open a new issue here and we can try to resolve it manually.
